In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('df_test.csv')

In [3]:
df.shape

(6700, 14)

In [4]:
df.head()

date     price  bedrooms  grade  has_basement  living_in_m2  \
0  2014-09-26  305000.0         2      1         False      76.18046   
1  2014-05-14  498000.0         3      2          True     210.88981   
2  2015-03-23  590000.0         2      4         False     262.91549   
3  2014-07-15  775000.0         3      3         False     159.79316   
4  2015-04-14  350000.0         2      1         False      92.90300   

   renovated  nice_view  perfect_condition  real_bathrooms  has_lavatory  \
0      False      False               True               1         False   
1      False      False              False               2          True   
2      False      False              False               2          True   
3      False      False              False               1          True   
4      False      False              False               1          True   

   single_floor  month  quartile_zone  
0          True      9              2  
1          True      5              2  
2         False      3              2  
3         False      7              3  
4          True      4              3

In [14]:
Y = df['price'].to_numpy()
X = df[['living_in_m2', 'real_bathrooms', 'month', 'quartile_zone']].to_numpy()
print(X.shape)
print(Y.shape)

(6700, 4)
(6700,)


In [12]:
Y[:5]

array([305000., 498000., 590000., 775000., 350000.])

In [13]:
X[:5]

array([[ 76.18046,   1.     ,   9.     ,   2.     ],
       [210.88981,   2.     ,   5.     ,   2.     ],
       [262.91549,   2.     ,   3.     ,   2.     ],
       [159.79316,   1.     ,   7.     ,   3.     ],
       [ 92.903  ,   1.     ,   4.     ,   3.     ]])

In [26]:
learning_rate = 0.00000001
n_iterations = 10

w = np.array([ 1585.88913476,  3180.14657637, -1733.24107787, 78183.67763556])
b = 4475.243908995045

m = X.shape[0]
for i in range(n_iterations):
    y_pred = np.dot(X, w) + b
    for j in range(w.shape[0]):
      w[j] -= learning_rate * (1/m) * np.sum((y_pred - Y) * X[:, j])
    b -= learning_rate * (1/m) * np.sum(y_pred - Y)
    print((1/m) * np.sum(y_pred - Y)) if i % 1 == 0 else None

[ 1585.88913171  3180.14657474 -1733.2411194  78183.67799898] 4475.243906670011 232.50337213358245
[ 1585.88912866  3180.14657311 -1733.24116093 78183.67836241] 4475.243904344977 232.5034219648272
[ 1585.88912561  3180.14657148 -1733.24120245 78183.67872583] 4475.243902019942 232.50347179606362
[ 1585.88912256  3180.14656985 -1733.24124398 78183.67908925] 4475.243899694907 232.5035216272815
[ 1585.88911951  3180.14656822 -1733.24128551 78183.67945267] 4475.243897369871 232.5035714585254
[ 1585.88911647  3180.14656659 -1733.24132704 78183.6798161 ] 4475.243895044835 232.5036212897877
[ 1585.88911342  3180.14656496 -1733.24136857 78183.68017952] 4475.243892719798 232.50367112100946
[ 1585.88911037  3180.14656333 -1733.24141009 78183.68054294] 4475.243890394761 232.50372095227624
[ 1585.88910732  3180.1465617  -1733.24145162 78183.68090636] 4475.243888069724 232.50377078351133
[ 1585.88910427  3180.14656008 -1733.24149315 78183.68126979] 4475.243885744685 232.5038206147062
